# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160504_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
