# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ManyToManyField(null=True, to='posts.Comments'),
        ),
    ]
