# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160504_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Comments'),
        ),
    ]
